### ISSUE TITLE
Author not reachable

### ISSUE THREAD

**Issue by mxa** [hamonikr/nimf#23]
The only author listed in AUTHORS; Hodong Kim is not using this gmail address any more. Emails to this address bounce.
I also miss any reference to his gitlab at https://gitlab.com/nimf-i18n/nimf

**Comment by mxa** [comment]
It looks like Hodong Kim became <s>paranoid</s> cautious about corporations such as Google (gmail) and Microsoft (github) so he migrated his project to gitlab and ended his gmail account, but no new contact address is available on his site and the gitlab has the issue tracker deactivated.

**Comment by chaeya** [comment]
@mxa I am Kevin, the developer of the HamoniKR project.

This project is currently being managed by the HamoniKR development team, because of the original author's project management became difficult.

I will modify the project documentation to reflect the address of the developer and issue management who can be contacted.

**Comment by chaeya** [comment]
@mxa I just updated AUTHOS document. Feel free to leave any issues related to this project.

https://github.com/hamonikr/nimf/commit/6b94b5fb988caf473101d9e1a1e68f676152ba78
